name: carnd-term1
channels:
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- defaults
dependencies:
- imageio=2.2.0=py35hcd4b9a4_0
- backports=1.0=py35_0
- backports.weakref=1.0rc1=py35_0
- bleach=1.5.0=py35_0
- bzip2=1.0.6=vc14_3
- certifi=2016.2.28=py35_0
- colorama=0.3.9=py35_0
- cycler=0.10.0=py35_0
- decorator=4.1.2=py35_0
- freetype=2.5.5=vc14_2
- html5lib=0.9999999=py35_0
- icu=57.1=vc14_0
- ipykernel=4.6.1=py35_0
- ipython=6.1.0=py35_0
- ipython_genutils=0.2.0=py35_0
- jedi=0.10.2=py35_2
- jpeg=9b=vc14_0
- jupyter_client=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- libpng=1.6.30=vc14_1
- libprotobuf=3.2.0=vc14_0
- libtiff=4.0.6=vc14_3
- markdown=2.6.9=py35_0
- matplotlib=2.0.2=np113py35_0
- mkl=2017.0.3=0
- numpy=1.13.1=py35_0
- olefile=0.44=py35_0
- openssl=1.0.2l=vc14_0
- pandas=0.20.3=py35_0
- path.py=10.3.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=4.2.1=py35_0
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.15=py35_0
- protobuf=3.2.0=py35_0
- pygments=2.2.0=py35_0
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- pyzmq=16.0.2=py35_0
- qt=5.6.2=vc14_6
- scikit-learn=0.19.0=np113py35_0
- scipy=0.19.1=np113py35_0
- setuptools=36.4.0=py35_1
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_1
- tensorflow=1.2.1=py35_0
- tk=8.5.18=vc14_0
- tornado=4.5.2=py35_0
- traitlets=4.3.2=py35_0
- vc=14=0
- vs2015_runtime=14.0.25420=0
- wcwidth=0.1.7=py35_0
- werkzeug=0.12.2=py35_0
- wheel=0.29.0=py35_0
- win_unicode_console=0.5=py35_0
- wincertstore=0.2=py35_0
- zlib=1.2.11=vc14_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.3.0
  - moviepy==0.2.3.2
  - opencv-python==3.4.0.12
  - prompt-toolkit==1.0.15
  - tqdm==4.11.2
  - win-unicode-console==0.5
prefix: C:\ProgramData\Anaconda2\envs\carnd-term1

